### ISSUE TITLE
Call to undefined function IslamicNetwork\PrayerTimes\gregoriantojd()

### ISSUE THREAD

**Issue by OussamaNahnah** [islamic-network/prayer-times#4]
I encountered an issue while using your library [prayer-times](https://github.com/islamic-network/prayer-times) in my Laravel 10 application (current version). When I run the command `php artisan serve`, it shows the following error:

![Error Screenshot](https://github.com/islamic-network/prayer-times/assets/33777905/8c6fb2a7-69ac-469c-a1b8-190148b5ea9d)

After some investigation, I found that the PHP function `gregoriantojd()` used in [line 533 of the PrayerTimes.php class](https://github.com/islamic-network/prayer-times/blob/7591493229a423778ebd8d813aed5e7fcb791ecd/src/PrayerTimes/PrayerTimes.php#L532) is not recognized by the current PHP version. My current PHP version is:

![PHP Version Screenshot](https://github.com/islamic-network/prayer-times/assets/33777905/1af2ef4d-879e-4426-aa31-60eef5fafd99)

The library works fine in Homestead, where the PHP version is:

![Homestead PHP Version Screenshot](https://github.com/islamic-network/prayer-times/assets/33777905/43b68292-5499-4e9e-a730-7cc27ec6301f)

**Additional Information:**
In addition, I noticed a discrepancy in [line 533 of the PrayerTimes.php class](https://github.com/islamic-network/prayer-times/blob/7591493229a423778ebd8d813aed5e7fcb791ecd/src/PrayerTimes/PrayerTimes.php#L532) . Specifically, it suggests receiving the year using `$this->date->format('y')`, but according to the PHP documentation, it should be received as `$this->date->format('Y')` to represent the four-digit year. Please consider updating this part of the code for consistency and compatibility.

Please advise on how to resolve this compatibility issue or if there is a recommended PHP version for using the `prayer-times` library.

Thank you!

**Comment by meezaan** [comment]
Thank you @OussamaNahnah. I'll have a look.

**Comment by meezaan** [comment]
There is nothing in the PHP documentation to say at https://www.php.net/manual/en/function.gregoriantojd.php to say that the method has been removed or deprecated in PHP 8.2.12. It's possible that this is a bug in the PHP binary you are using for 8.2.12, and definitely a possibility if you are using a mac.

The year I have just committed a fix for - https://github.com/islamic-network/prayer-times/commit/f32baaaf7480c133bb45f1b972447e0a7c76b439. 

I need to add a couple more methods to the library for the calculation. I will also test it out on a newer version of PHP 8.2 and then release a new version of the library.

Please expect something either tomorrow or Monday, inshaAllah!

The AlAdhan API uses PHP 8.2 and runs 8.2.8 (upgrade due soon) without any problems.

**Comment by OussamaNahnah** [comment]
Thank you so much for your response. You're doing great, brother. I just wanted to bring something to your attention. I am using Manjaro KDE (Manjaro 23.1.0 Vulcan) and have two laptops with the same Linux system, both running PHP version 8.2.12. However, I am still encountering the same error. I even tried PHP version 8.1.25, but the issue persists.

Here is a screenshot of the error: ![Screenshot_20231118_220010](https://github.com/islamic-network/prayer-times/assets/33777905/bdd4f72e-330e-4e54-a441-65211cba965d)

I suspect that the problem may be related to the PHP packages in the Arch Linux repositories.

**Comment by meezaan** [comment]
https://github.com/islamic-network/prayer-times/releases/tag/1.0.25 has been released. 

I'll test the PHP issues on Debian and Ubuntu at least as I incorporate the change into the API.

**Comment by meezaan** [comment]
I can confirm that there are no problems with 8.12.12 running on Debian with the following build:

```
PHP 8.2.12 (cli) (built: Nov  1 2023 06:02:56) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.12, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.12, Copyright (c), by Zend Technologies
```

**Comment by OussamaNahnah** [comment]
Hi @meezaan,

I hope you are well. I conducted some research on the PHP issue and identified the absence of the PHP calendar extension as the root cause. I resolved this by compiling PHP and incorporating additional extensions (openssl, calendar, curl) from the source code. I will share the detailed steps on how I did this soon on my [LinkedIn](https://www.linkedin.com/in/oussamanahnah/). The solution worked effectively.

I tested the new version and observed improved accuracy. I conducted the test using Setif, Algeria, as the coordination parameter.

```json
 {
    "Fajr": "05:50" // +1min in real-time,
    "Sunrise": "07:19" // +1min in real-time,
    "Dhuhr": "12:24" // +1min in real-time,
    "Asr": "15:09" // +1min in real-time,
    "Maghrib": "17:28" // +5min in real-time,
    "Isha": "18:53" // +1min in real-time
}

```

I want to express my gratitude once again. Thank you.

**Comment by meezaan** [comment]
> Hi @meezaan,
> 
> 
> 
> I hope you are well. I conducted some research on the PHP issue and identified the absence of the PHP calendar extension as the root cause. I resolved this by compiling PHP and incorporating additional extensions (openssl, calendar, curl) from the source code. I will share the detailed steps on how I did this soon on my [LinkedIn](https://www.linkedin.com/in/oussamanahnah/). The solution worked effectively.
> 
> 
> 
> I tested the new version and observed improved accuracy. I conducted the test using Setif, Algeria, as the coordination parameter.
> 
> 
> 
> ```json
> 
>  {
> 
>     "Fajr": "05:50" // +1min in real-time,
> 
>     "Sunrise": "07:19" // +1min in real-time,
> 
>     "Dhuhr": "12:24" // +1min in real-time,
> 
>     "Asr": "15:09" // +1min in real-time,
> 
>     "Maghrib": "17:28" // +5min in real-time,
> 
>     "Isha": "18:53" // +1min in real-time
> 
> }
> 
> 
> 
> ```
> 
> 
> 
> I want to express my gratitude once again. Thank you.

Alhamdulillah, that's brilliant. All praise belongs to Allah SWT. May He accept from us all!
